import { CrudResource, DataError, DataResult, ListQuery, ListResult, RemoveOptions, UpdateOptions } from "./contracts.js";
type Stored<T> = { id: number; etag: string; value: T };
export type LocalCrudOptions<TEntity, TCreate, TUpdate> = { initial?: readonly TEntity[]; getId?: (entity: TEntity) => number; toEntity?: (input: TCreate, id: number) => TEntity; applyUpdate?: (entity: TEntity, input: TUpdate) => TEntity; validateCreate?: (input: TCreate) => void; validateUpdate?: (input: TUpdate) => void };
const clone = <T>(value: T): T => structuredClone(value);
export class LocalCrudResource<TEntity extends object, TCreate, TUpdate> implements CrudResource<TEntity, TCreate, TUpdate> {
  private nextId = 1; private readonly rows = new Map<number, Stored<TEntity>>();
  private readonly toEntity: (input: TCreate, id: number) => TEntity; private readonly applyUpdate: (entity: TEntity, input: TUpdate) => TEntity;
  constructor(private readonly options: LocalCrudOptions<TEntity, TCreate, TUpdate>) {
    this.toEntity = options.toEntity ?? ((input, id) => ({ ...input, id } as unknown as TEntity)); this.applyUpdate = options.applyUpdate ?? ((entity, input) => ({ ...entity, ...input } as unknown as TEntity));
    for (const entity of options.initial ?? []) { const candidate = options.getId?.(entity) ?? (entity as { id?: number }).id; if (typeof candidate !== "number" || !Number.isInteger(candidate) || candidate < 1) throw new DataError("validation", "Initial entity has an invalid id"); const id = candidate; if (this.rows.has(id)) throw new DataError("conflict", "Duplicate id"); this.rows.set(id, { id, etag: "1", value: clone(entity) }); this.nextId = Math.max(this.nextId, id + 1); }
  }
  private row(id: number): Stored<TEntity> { const row = this.rows.get(id); if (!row) throw new DataError("not-found", `Entity ${id} was not found`); return row; }
  private check(row: Stored<TEntity>, etag?: string): void { if (etag !== undefined && etag !== row.etag) throw new DataError("conflict", "The entity has changed", { expected: etag, actual: row.etag }); }
  async list(query?: ListQuery): Promise<ListResult<TEntity>> { const pageSize = query?.pageSize ?? 100; if (!Number.isInteger(pageSize) || pageSize < 1) throw new DataError("validation", "pageSize must be a positive integer"); if (query?.top !== undefined && (!Number.isInteger(query.top) || query.top < 0)) throw new DataError("validation", "top must be a non-negative integer"); if (query?.maxPages !== undefined && (!Number.isInteger(query.maxPages) || query.maxPages < 0)) throw new DataError("validation", "maxPages must be a non-negative integer"); let limit = this.rows.size; if (query?.top !== undefined) limit = Math.min(limit, query.top); if (query?.maxPages !== undefined) limit = Math.min(limit, pageSize * query.maxPages); const selected = [...this.rows.values()].slice(0, limit); return { data: selected.map(row => clone(row.value)), etags: Object.fromEntries(selected.map(row => [String(row.id), row.etag])) }; }
  async get(id: number): Promise<DataResult<TEntity>> { const row = this.row(id); return { data: clone(row.value), etag: row.etag }; }
  async create(input: TCreate): Promise<DataResult<TEntity>> { try { this.options.validateCreate?.(input); const id = this.nextId++; const value = clone(this.toEntity(input, id)); this.rows.set(id, { id, etag: "1", value }); return { data: clone(value), etag: "1" }; } catch (e) { throw e instanceof DataError ? e : new DataError("validation", "Create input is invalid", e); } }
  async update(id: number, input: TUpdate, options?: UpdateOptions): Promise<DataResult<TEntity>> { const row = this.row(id); this.check(row, options?.etag); try { this.options.validateUpdate?.(input); row.value = clone(this.applyUpdate(clone(row.value), input)); row.etag = String(Number(row.etag) + 1); return { data: clone(row.value), etag: row.etag }; } catch (e) { throw e instanceof DataError ? e : new DataError("validation", "Update input is invalid", e); } }
  async remove(id: number, options?: RemoveOptions): Promise<DataResult<void>> { const row = this.row(id); this.check(row, options?.etag); this.rows.delete(id); return { data: undefined }; }
  etag(id: number): string { return this.row(id).etag; }
}
